/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package operaciones;

/**
 *
 * @author alexl
 */
public class inicio extends javax.swing.JFrame {

    /**
     * Creates new form inicio
     *
     **
     * Declaro los objetos de Opereaciones.java
     */
    operaciones operar = new operaciones();

    public inicio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cbxOPC = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        txt1 = new javax.swing.JLabel();
        txtResp = new javax.swing.JTextField();
        txt2 = new javax.swing.JLabel();
        convertir = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        resp = new javax.swing.JTextField();
        limpiar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cbxOPC.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Binario", "Decimal", "Octal", "Hexadecimal" }));
        cbxOPC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxOPCActionPerformed(evt);
            }
        });
        getContentPane().add(cbxOPC, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, 286, -1));

        jLabel1.setFont(new java.awt.Font("Rockwell", 0, 24)); // NOI18N
        jLabel1.setText("CONVERSOR");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(133, 15, -1, -1));

        txt1.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        txt1.setText("Número:");
        getContentPane().add(txt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 81, -1, -1));

        txtResp.setText("0");
        txtResp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRespActionPerformed(evt);
            }
        });
        getContentPane().add(txtResp, new org.netbeans.lib.awtextra.AbsoluteConstraints(92, 78, 286, -1));

        txt2.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        txt2.setText("Base:");
        getContentPane().add(txt2, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 124, -1, -1));

        convertir.setText("Convertir");
        convertir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                convertirActionPerformed(evt);
            }
        });
        getContentPane().add(convertir, new org.netbeans.lib.awtextra.AbsoluteConstraints(298, 152, 80, -1));

        jLabel2.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        jLabel2.setText("Resultado:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 200, -1, -1));

        resp.setText("0");
        resp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                respActionPerformed(evt);
            }
        });
        getContentPane().add(resp, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 228, 353, -1));

        limpiar.setText("Limpiar");
        limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limpiarActionPerformed(evt);
            }
        });
        getContentPane().add(limpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(298, 190, 80, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/operaciones/mine-696x392.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-200, 0, 600, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbxOPCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxOPCActionPerformed
        // TODO add your handling code here:


    }//GEN-LAST:event_cbxOPCActionPerformed

    private void txtRespActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRespActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRespActionPerformed

    private void convertirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_convertirActionPerformed
        // Acción del boton
        
        int numero = Integer.parseInt(txtResp.getText());
        int base = 0;
        //Obtener la respuesta del box
        int i = cbxOPC.getSelectedIndex();
        System.out.println("INDEX :::::>" + i+"\n"+resp);
        switch (i) {
            case 0:
                base = 2;
                break;
            case 1:
                base = 10;
                break;
            case 2:
                base = 8;
                break;
            case 3:
                base = 16;
                break;
            default:
                
                
        }
      
         Base bases = new Base(numero, base);
        bases.transformar();
        //Operaciones
        

       
        resp.setText(bases.getResultado());
    }//GEN-LAST:event_convertirActionPerformed

    private void respActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_respActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_respActionPerformed

    private void limpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limpiarActionPerformed

        // TODO add your handling code here:
        txtResp.setText("");
        resp.setText("");
        
        
    }//GEN-LAST:event_limpiarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
       
      
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
       
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cbxOPC;
    private javax.swing.JButton convertir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton limpiar;
    private javax.swing.JTextField resp;
    private javax.swing.JLabel txt1;
    private javax.swing.JLabel txt2;
    private javax.swing.JTextField txtResp;
    // End of variables declaration//GEN-END:variables
}
